### PR TITLE
Pretty Printing

### PR DESCRIPTION
**Pull request by trajafri**
Thought of a simple way to combine "text image"s like `2htdp` images are combined, so figured I will experiment here :)

`text_image.py` exports a `TextImage` class which behaves like a `2htdp` image

You can use the following APIs to combine different images:
* `beside`: works like [(beside/align "bottom" ...)](https://docs.racket-lang.org/teachpack/2htdpimage.html#%28def._%28%28lib._2htdp%2Fimage..rkt%29._beside%2Falign%29%29)
* `above`: works just like [above](https://docs.racket-lang.org/teachpack/2htdpimage.html#%28def._%28%28lib._2htdp%2Fimage..rkt%29._above%29%29)
* `aboveStr`: Shortcut for `some_text_image.above(TextImage(str))`

here's some sample proof trees:

```
                                                                                                                                                               
                                                       --------- given  --------- given              --------- given  --------- given                           
                                                        All d e          All e f                      All f g          All g i                                  
      --------- given  --------- given              ------------------------------------ barbara  ------------------------------------ barbara                  
       All b c          All c d                                       All d f                                       All f i                                     
   ------------------------------------ barbara  ---------------------------------------------------------------------------------------------- barbara         
                     All b d                                                                    All d i                                                         
-------------------------------------------------------------------------------------------------------------------------------------------------------- barbara
                                                                            All b i                                                                             

```

```
                          --------- given  --------- given  --------- given                                                                                                  
                           All b c          All c d          All d e                                                                                                         
      --------- given  ----------------------------------------------------- max2                               --------- given  --------- given  --------- axiom            
       All a b                                  All b e                                                          All f g          All g h          All h h                   
   ------------------------------------------------------------------------------- barbara  --------- given  ----------------------------------------------------- max2      
                                           All a e                                           All e f                                  All f h                                
------------------------------------------------------------------------------------------------------------------------------------------------------------------------ max2
                                                                                   All a h                                                                                   

```

### CODE REVIEW

**Comment by trajafri** [comment]
might add unit tests if this seems useful

**Comment by lmoss** [comment]
Hi Turab,

Nice to have your name and work flash on my screen.   I hope you're well.

Your pretty-printer works by recursion, right?   

I once wrote a special case of the program that Annie is writing (actually a very special case), and the proofs were stored in a way that gave rise to trees pretty easily.  But I never figured out how to do the pretty-printing.   So that was one reason for moving to the numbered lists.  The second reason was that for teaching purposes, the numbered lists are more standard (I think).   But it would be really great to have both formats.

      Larry

**Comment by trajafri** [comment]
It indeed works with recursion! you can see that happening [here](https://github.com/trajafri/natlogic/blob/feac7ea45288e48995a37c8c3fa1d2592c199250/impsubset/subsetInf.py#L198)

This seems like a very cool project, excited to see what else is gonna happen here :)

**Comment by annrpom** [comment]
thnx turbo

**Pull request merged**
